#!/usr/bin/env python
import Image,os
from random import randint

w,h=20,10

img=Image.new('RGB',(w,h))

def get_gray(l,h):
	gray = randint(l,h)
	return (gray<<16)+(gray<<8)+gray

for x in range(w):
	for y in range(h):
		img.putpixel((x,y),get_gray(0x22,0x33))

img.save(os.path.expanduser('~/.wallpaper.png'))
os.system('feh --bg-tile ~/.wallpaper.png')
