#!/usr/bin/env node

process.stdin.resume()
process.stdin.setEncoding('utf8')

let input = ''
process.stdin.on('data', chunk => input += chunk)

process.stdin.on('end', () => {
  console.log([...new Set(input.match(/[0-9]{16}/g))].join(','))
})

