#!/usr/bin/env node

const url = require('url')

process.stdin.resume()
process.stdin.setEncoding('utf8')

let input = ''
process.stdin.on('data', chunk => input += chunk)

process.stdin.on('end', () => console.log(url.parse(input, true)))

